// Package service keeps the relay alive across logout, reboot and
// crashes.
//
// Each platform has one obvious mechanism, so this package wraps that
// mechanism rather than shipping a daemon manager of its own. Every
// manager is user-level: the relay needs no privileges, it needs the
// logged-in session's Bluetooth access, and a user service starts at
// login. Installing system-wide would prompt for a password and gain
// nothing.
package service

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// Manager installs and controls the background relay service.
//
// Install and Uninstall are idempotent. Start, Stop and Disable act on an
// installed service and report an error if it is missing.
type Manager interface {
	// Install writes the service definition and enables it at login.
	Install(binPath string) error

	// Uninstall stops the service and removes its definition.
	Uninstall() error

	// Start launches the service now.
	Start() error

	// Stop halts the service until the next login.
	Stop() error

	// Disable stops the service and prevents it starting at login.
	Disable() error

	// Running reports whether the service is currently up.
	Running() (bool, error)

	// Command returns the underlying platform invocation, so that
	// `stoplight status` can print it. The wrapper is never a black box:
	// launchctl and systemctl still work directly, and a user who wants
	// to bypass this package needs to see what it ran.
	Command() string
}

// New returns the Manager for the current platform.
//
// The build tags on the platform files mean exactly one newManager is
// compiled in. An unsupported GOOS fails here rather than at build time,
// because the rest of the binary is portable and worth building anyway.
func New() (Manager, error) {
	return newManager()
}

// errUnsupported reports a platform with no service manager.
func errUnsupported() error {
	return fmt.Errorf("no service manager for %s: run the relay yourself with `stoplight relay`", runtime.GOOS)
}

// stateDir is where the service writes its log.
//
// This matches the relay's own default so that `stoplight logs` and the
// service definition agree on one path.
func stateDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("find the home directory: %w", err)
	}
	return filepath.Join(home, ".local", "state", "stoplight"), nil
}

// logPath is the file the service manager redirects output to.
func logPath() (string, error) {
	dir, err := stateDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "stoplight.log"), nil
}

// resolveTarget follows a symlink to the file that should actually be
// written, so that renaming does not replace the link with a regular
// file. A path that does not exist yet is returned unchanged.
func resolveTarget(path string) (string, error) {
	resolved, err := filepath.EvalSymlinks(path)
	if err == nil {
		return resolved, nil
	}
	if !os.IsNotExist(err) {
		return "", fmt.Errorf("resolve %s: %w", path, err)
	}

	// Either the path is missing, or it is a link to something missing.
	// Follow one level so a broken link is written through, not replaced.
	info, lerr := os.Lstat(path)
	if lerr != nil || info.Mode()&os.ModeSymlink == 0 {
		return path, nil
	}
	dest, lerr := os.Readlink(path)
	if lerr != nil {
		return "", fmt.Errorf("read the link %s: %w", path, lerr)
	}
	if !filepath.IsAbs(dest) {
		dest = filepath.Join(filepath.Dir(path), dest)
	}
	return dest, nil
}

// serviceMarker identifies a service definition this package generated.
//
// It goes in a comment line, which every format here tolerates, so that a
// plist or unit file already at our path can be told apart from one we
// wrote. Without it Install overwrites and Uninstall deletes whatever it
// finds: a definition from a package manager, from a colleague's
// dotfiles, or from the user's own hand.
const serviceMarker = "Generated by Stoplight. Do not edit: `stoplight install` overwrites this file."

// markerComments are the comment openings this package writes the marker
// behind: "# " in a systemd unit, "<!-- " in a launchd plist. A line may
// also carry the marker with no opening at all, which is what a format
// with no comment syntax would need.
var markerComments = []string{"#", "<!--"}

// owned reports whether the file at path may be written or deleted.
//
// A path with nothing at it is free to use. A file that carries the
// marker as a line of its own is one of ours. Anything else belongs to
// somebody else, and an unreadable file is treated as theirs, because a
// guess in the other direction destroys it.
//
// The test is the marker starting its own line, not the marker anywhere
// in the file. An unanchored substring claims any file that merely
// mentions the text, so a unit whose Description quoted our warning would
// be overwritten by Install and deleted by Uninstall. This mirrors the
// Claude Code adapter, which anchors on a prefix for the same reason.
func owned(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return os.IsNotExist(err)
	}
	for _, line := range bytes.Split(data, []byte("\n")) {
		if isMarkerLine(string(line)) {
			return true
		}
	}
	return false
}

// isMarkerLine reports whether one line is the marker on its own, with an
// optional comment opening.
//
// Surrounding whitespace and a plist's closing "-->" are tolerated,
// because an editor may reflow either without changing whose file it is.
func isMarkerLine(line string) bool {
	text := strings.TrimSpace(line)
	for _, open := range markerComments {
		if strings.HasPrefix(text, open) {
			text = strings.TrimSpace(strings.TrimPrefix(text, open))
			break
		}
	}
	text = strings.TrimSpace(strings.TrimSuffix(text, "-->"))
	return text == serviceMarker
}

// checkOwned turns the ownership test into the error the user sees.
func checkOwned(path string) error {
	if owned(path) {
		return nil
	}
	return fmt.Errorf("%s was not written by Stoplight: move or delete it first, it has not been changed", path)
}

// writeFileAtomic writes data to path through a temporary file in the
// same directory.
//
// A service manager may read the definition at any moment, including
// while it is being rewritten, so it must never see a partial file.
//
// perm applies only when the file is new. An existing file keeps the
// permissions it has, so that a user who tightened a definition to 0600
// does not find it back at 0644 after the next install.
// A symlinked definition is written through to its target, so a plist or
// unit symlinked into a dotfiles repo keeps its link.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	target, err := resolveTarget(path)
	if err != nil {
		return err
	}

	dir := filepath.Dir(target)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}

	tmp, err := os.CreateTemp(dir, ".stoplight-*")
	if err != nil {
		return fmt.Errorf("create a temporary file in %s: %w", dir, err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("write %s: %w", tmpName, err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("sync %s: %w", tmpName, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close %s: %w", tmpName, err)
	}
	// Carry the existing permissions rather than forcing the caller's.
	if info, err := os.Stat(path); err == nil {
		perm = info.Mode().Perm()
	}
	if err := os.Chmod(tmpName, perm); err != nil {
		return fmt.Errorf("set permissions on %s: %w", tmpName, err)
	}
	if err := os.Rename(tmpName, target); err != nil {
		return fmt.Errorf("replace %s: %w", target, err)
	}
	return nil
}
